# Generated by Django 2.0.7 on 2018-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopenings',
            name='job_contperson',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_id',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_postdt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
