# Generated by Django 2.0.7 on 2018-07-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_auto_20180704_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_contperson',
            new_name='job_Contact_Person',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_desc',
            new_name='job_Desc',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_id',
            new_name='job_Id',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_openings',
            new_name='job_Openings',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_position',
            new_name='job_Position',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_postdt',
            new_name='job_Post_Date',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_skill_set',
            new_name='job_Skill_set',
        ),
        migrations.RenameField(
            model_name='jobopenings',
            old_name='job_status',
            new_name='job_Status',
        ),
    ]
